//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataMiningTeam.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SalesItemsetsEntity> SalesItemsetsEntities
        {
            get
            {
                if ((_SalesItemsetsEntities == null))
                {
                    _SalesItemsetsEntities = base.CreateObjectSet<SalesItemsetsEntity>("SalesItemsetsEntities");
                }
                return _SalesItemsetsEntities;
            }
        }
        private ObjectSet<SalesItemsetsEntity> _SalesItemsetsEntities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SalesItemsetsEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalesItemsetsEntities(SalesItemsetsEntity salesItemsetsEntity)
        {
            base.AddObject("SalesItemsetsEntities", salesItemsetsEntity);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="SalesItemsetsEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SalesItemsetsEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalesItemsetsEntity object.
        /// </summary>
        /// <param name="salesorder">Initial value of the salesorder property.</param>
        public static SalesItemsetsEntity CreateSalesItemsetsEntity(global::System.String salesorder)
        {
            SalesItemsetsEntity salesItemsetsEntity = new SalesItemsetsEntity();
            salesItemsetsEntity.salesorder = salesorder;
            return salesItemsetsEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salesorder
        {
            get
            {
                return _salesorder;
            }
            set
            {
                if (_salesorder != value)
                {
                    OnsalesorderChanging(value);
                    ReportPropertyChanging("salesorder");
                    _salesorder = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("salesorder");
                    OnsalesorderChanged();
                }
            }
        }
        private global::System.String _salesorder;
        partial void OnsalesorderChanging(global::System.String value);
        partial void OnsalesorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Products
        {
            get
            {
                return _Products;
            }
            set
            {
                OnProductsChanging(value);
                ReportPropertyChanging("Products");
                _Products = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Products");
                OnProductsChanged();
            }
        }
        private global::System.String _Products;
        partial void OnProductsChanging(global::System.String value);
        partial void OnProductsChanged();

        #endregion

    
    }

    #endregion

    
}
