//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DataMiningTeam.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdventureWorksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdventureWorksEntities object using the connection string found in the 'AdventureWorksEntities' section of the application configuration file.
        /// </summary>
        public AdventureWorksEntities() : base("name=AdventureWorksEntities", "AdventureWorksEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(string connectionString) : base(connectionString, "AdventureWorksEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(EntityConnection connection) : base(connection, "AdventureWorksEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SalesItemsetsEntity> SalesItemsetsEntities
        {
            get
            {
                if ((_SalesItemsetsEntities == null))
                {
                    _SalesItemsetsEntities = base.CreateObjectSet<SalesItemsetsEntity>("SalesItemsetsEntities");
                }
                return _SalesItemsetsEntities;
            }
        }
        private ObjectSet<SalesItemsetsEntity> _SalesItemsetsEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookExampleEntity> BookExampleEntities
        {
            get
            {
                if ((_BookExampleEntities == null))
                {
                    _BookExampleEntities = base.CreateObjectSet<BookExampleEntity>("BookExampleEntities");
                }
                return _BookExampleEntities;
            }
        }
        private ObjectSet<BookExampleEntity> _BookExampleEntities;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SalesItemsetsEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalesItemsetsEntities(SalesItemsetsEntity salesItemsetsEntity)
        {
            base.AddObject("SalesItemsetsEntities", salesItemsetsEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookExampleEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookExampleEntities(BookExampleEntity bookExampleEntity)
        {
            base.AddObject("BookExampleEntities", bookExampleEntity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="BookExampleEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookExampleEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookExampleEntity object.
        /// </summary>
        /// <param name="tID">Initial value of the TID property.</param>
        /// <param name="items">Initial value of the items property.</param>
        public static BookExampleEntity CreateBookExampleEntity(global::System.String tID, global::System.String items)
        {
            BookExampleEntity bookExampleEntity = new BookExampleEntity();
            bookExampleEntity.TID = tID;
            bookExampleEntity.items = items;
            return bookExampleEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.String _TID;
        partial void OnTIDChanging(global::System.String value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String items
        {
            get
            {
                return _items;
            }
            set
            {
                if (_items != value)
                {
                    OnitemsChanging(value);
                    ReportPropertyChanging("items");
                    _items = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("items");
                    OnitemsChanged();
                }
            }
        }
        private global::System.String _items;
        partial void OnitemsChanging(global::System.String value);
        partial void OnitemsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="SalesItemsetsEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SalesItemsetsEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalesItemsetsEntity object.
        /// </summary>
        /// <param name="salesorder">Initial value of the salesorder property.</param>
        public static SalesItemsetsEntity CreateSalesItemsetsEntity(global::System.String salesorder)
        {
            SalesItemsetsEntity salesItemsetsEntity = new SalesItemsetsEntity();
            salesItemsetsEntity.salesorder = salesorder;
            return salesItemsetsEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salesorder
        {
            get
            {
                return _salesorder;
            }
            set
            {
                if (_salesorder != value)
                {
                    OnsalesorderChanging(value);
                    ReportPropertyChanging("salesorder");
                    _salesorder = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("salesorder");
                    OnsalesorderChanged();
                }
            }
        }
        private global::System.String _salesorder;
        partial void OnsalesorderChanging(global::System.String value);
        partial void OnsalesorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Products
        {
            get
            {
                return _Products;
            }
            set
            {
                OnProductsChanging(value);
                ReportPropertyChanging("Products");
                _Products = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Products");
                OnProductsChanged();
            }
        }
        private global::System.String _Products;
        partial void OnProductsChanging(global::System.String value);
        partial void OnProductsChanged();

        #endregion
    
    }

    #endregion
    
}
